### ISSUE TITLE
Customize default hotkey to open modal is not available 

### ISSUE THREAD

**Issue by lukleo** [bigkemp/Salesforce-Quick-Access-Bar#19]
Hi, I reset my Chrome and reinstalled this wonderful app, but I missed the config for one of my unsynced profiles. Then I realized that isn't possible to change the default hotkey to open modal anymore. I use command + / for my other profiles, but I can't change it in this newly installed profile from Command+k.

Ps.: I can't even change the others from command + / to any other combination too (unless I reinstall it to go back to command _ k, I suppose)

Did you remove this feature? It was really good.

**Comment by bigkemp** [comment]
Hi Lukleo, thank you for you reaching out and Im glad you like the extension!
Im guessing you didnt find the tab for the setting page?
the feature to change the hotkey is still available, I just replaced the setting icon to a side panel.
you will see once the modal is open a small white tab on the right side, that will open the setting page there you will have the preferences tab where you can change the hotkey.
you can see it here:
https://youtu.be/z-KSy1r-wwA?si=aBaWOJr3hXSsWQz2&t=126

let me know if this solve your issue

**Comment by lukleo** [comment]
Cool, I totally missed that, I took a quick look in the GitHub home page
and didn't find it as well sorry about that. Keep pushing the good work.
Thanks

**Comment by bigkemp** [comment]
Glad this resolved your issue!
I will be sure to update the tutorials in the homepage 
Im closing this ticket then...
be sure to stay tuned to the new update coming soon!
